/**
 * A hand-transcribed snapshot of every configurable, non-learned variable in
 * config/*.yaml that a decision, model, or eligibility gate reads — pulled from
 * TrackShift AGENTS.md / MODELS.md / API.md and the YAML files themselves
 * (config/rules/2026/common.yaml, config/physics/priors.yaml,
 * config/value/dp_development.yaml, config/state_discretization.yaml,
 * config/baselines.yaml, config/lap_classification.yaml,
 * config/tyre_pace.yaml). Read-only backing data for the /config explorer.
 *
 * This is a SNAPSHOT, not a live read of the YAML — the two can drift as those
 * files are edited. `snapshotOf` names the files it was taken from; re-derive
 * this array by hand (or wire a real YAML loader) if the numbers here stop
 * matching config/*.yaml. Every entry keeps its source file + dotted path so
 * that check is always a straight diff.
 */

export type ValueSource =
  | "RULE_FIA"
  | "OBSERVED_RCM"
  | "OBSERVED"
  | "DERIVED_TELEMETRY"
  | "PROXY_HISTORICAL_DRS"
  | "UNVERIFIED"
  | "DEVELOPMENT_ONLY";

export type InputKind = "number" | "list-number" | "list-string" | "select" | "boolean";

export interface ConfigVariable {
  id: string;
  label: string;
  file: string;
  path: string;
  value: number | boolean | number[] | string[] | null;
  unit?: string;
  valueSource: ValueSource;
  source: string;
  note?: string;
  /** Which models / decisions / API.md routes consume this value. */
  affects: string[];
  inputKind: InputKind;
  options?: string[];
  min?: number;
  max?: number;
  step?: number;
}

export interface ConfigCategory {
  id: string;
  title: string;
  description: string;
  variables: ConfigVariable[];
}

export const snapshotOf = [
  "config/rules/2026/common.yaml",
  "config/physics/priors.yaml",
  "config/value/dp_development.yaml",
  "config/state_discretization.yaml",
  "config/baselines.yaml",
  "config/lap_classification.yaml",
  "config/tyre_pace.yaml",
] as const;

export const CONFIG_CATEGORIES: ConfigCategory[] = [
  {
    id: "overtake-regulation",
    title: "Overtake & regulation thresholds",
    description:
      "The 2026 Overtake state machine and legal action set (M18 → M20 → M19 → M21). Everything here is external regulation, never a learned parameter — the rule engine refuses to start against an UNVERIFIED value once strict_mode is true.",
    variables: [
      {
        id: "detection_gap_s",
        label: "Detection Line gap threshold",
        file: "config/rules/2026/common.yaml",
        path: "overtake.detection_gap_s.value",
        value: 1.0,
        unit: "s",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Sporting Regulations, Overtake article",
        note: "The long-standing DRS threshold, carried over as a plausible starting point — not a 2026 citation.",
        affects: ["M20 Overtake state machine", "M07 opportunity dataset", "POST /rules/eligibility"],
        inputKind: "number",
        min: 0,
        max: 3,
        step: 0.05,
      },
      {
        id: "power_envelope_normal_breakpoints",
        label: "Normal-mode power envelope — breakpoints",
        file: "config/rules/2026/common.yaml",
        path: "overtake.power_envelope.normal.breakpoints_kmh",
        value: [0, 290, 340],
        unit: "km/h",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Technical Regulations, MGU-K deployment vs speed",
        note: "Full power to ~290 km/h, tapering to zero by ~340 km/h. Paired 1:1 with max_power_kw below.",
        affects: ["M19 max_electrical_power_kw", "M22 DP action space", "GET /rules/{event}/power_envelope"],
        inputKind: "list-number",
      },
      {
        id: "power_envelope_normal_power",
        label: "Normal-mode power envelope — max power",
        file: "config/rules/2026/common.yaml",
        path: "overtake.power_envelope.normal.max_power_kw",
        value: [350, 350, 0],
        unit: "kW",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Technical Regulations, MGU-K deployment vs speed",
        affects: ["M19 max_electrical_power_kw", "M22 DP action space"],
        inputKind: "list-number",
      },
      {
        id: "power_envelope_override_breakpoints",
        label: "Override-mode power envelope — breakpoints",
        file: "config/rules/2026/common.yaml",
        path: "overtake.power_envelope.override.breakpoints_kmh",
        value: [0, 337, 355],
        unit: "km/h",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Sporting/Technical Regulations, Overtake override",
        note: "~350 kW to ~337 km/h, available to ~355 km/h.",
        affects: ["M19 max_electrical_power_kw", "M35 override discriminator"],
        inputKind: "list-number",
      },
      {
        id: "power_envelope_override_power",
        label: "Override-mode power envelope — max power",
        file: "config/rules/2026/common.yaml",
        path: "overtake.power_envelope.override.max_power_kw",
        value: [350, 350, 0],
        unit: "kW",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Sporting/Technical Regulations, Overtake override",
        affects: ["M19 max_electrical_power_kw", "M35 override discriminator"],
        inputKind: "list-number",
      },
      {
        id: "separation_speed_kmh",
        label: "Envelope separation speed",
        file: "config/rules/2026/common.yaml",
        path: "overtake.power_envelope.separation_speed_kmh.value",
        value: 290,
        unit: "km/h",
        valueSource: "UNVERIFIED",
        source: "derived from the two curves above; not independently sourced",
        note: "Below this speed the curves coincide, override confers no advantage, and mode is not observable — M35 must return UNKNOWN, never NORMAL, below it.",
        affects: ["M35 override / ERS-mode discriminator", "ErsState.discriminable"],
        inputKind: "number",
        min: 0,
        max: 400,
        step: 5,
      },
      {
        id: "energy_deploy_limit_per_lap_mj",
        label: "Deploy limit per lap",
        file: "config/rules/2026/common.yaml",
        path: "energy.deploy_limit_per_lap_mj.value",
        value: null,
        unit: "MJ",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Technical Regulations, energy flow limits",
        affects: ["M19 legal_actions", "C5 energy twin accounting"],
        inputKind: "number",
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        id: "energy_harvest_limit_per_lap_mj",
        label: "Harvest limit per lap",
        file: "config/rules/2026/common.yaml",
        path: "energy.harvest_limit_per_lap_mj.value",
        value: null,
        unit: "MJ",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Technical Regulations, recovery limits",
        affects: ["M19 legal_actions", "C5 energy twin accounting"],
        inputKind: "number",
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        id: "energy_store_capacity_mj",
        label: "Energy Store capacity",
        file: "config/rules/2026/common.yaml",
        path: "energy.store_capacity_mj.value",
        value: null,
        unit: "MJ",
        valueSource: "UNVERIFIED",
        source: "TODO: FIA 2026 Technical Regulations, Energy Store capacity",
        note: "The physical bound on ers_soc_est_mj — a different constraint from the per-lap flow limits above. Conflating them produces a twin that is right about total energy and wrong about what the car may legally do next.",
        affects: ["C5 twin (ers_store_capacity_mj)", "ErsState.ers_soc_est_mj bound"],
        inputKind: "number",
        min: 0,
        max: 10,
        step: 0.1,
      },
      {
        id: "overtake_disabled_conditions",
        label: "Conditions that disable Overtake",
        file: "config/rules/2026/common.yaml",
        path: "race_control.overtake_disabled_conditions.value",
        value: ["SAFETY_CAR", "VIRTUAL_SAFETY_CAR", "RED_FLAG", "WET_DECLARED"],
        valueSource: "OBSERVED_RCM",
        source: "artifacts/race_control/2026_*.json, generated by scripts/data/extract_race_control.py",
        note: "Observed association from the 2026 rcm.json feed (51 enable / 23 disable messages), not a cited regulation.",
        affects: ["M02/C7 normal_race_model_eligible gate", "race_control.overtake_disabled"],
        inputKind: "list-string",
      },
      {
        id: "strict_mode",
        label: "Strict mode",
        file: "config/rules/2026/common.yaml",
        path: "strict_mode",
        value: false,
        valueSource: "OBSERVED",
        source: "operational switch, set by whoever runs the build",
        note: "Set true before any demo claim. The rule engine then refuses to run against UNVERIFIED or PROXY_* values, so a claim can never rest on an unsourced number.",
        affects: ["CP-11 rule engine start guard", "every §57/§58 legality claim"],
        inputKind: "boolean",
      },
    ],
  },
  {
    id: "physics-priors",
    title: "Physics priors (energy twin)",
    description:
      "Starting values for the longitudinal power-balance model (M14). CP-20 fits all five calibration rungs against these, and every value here is expected to move away from its literature starting point once calibrated.",
    variables: [
      {
        id: "chassis_minimum_kg",
        label: "Chassis minimum mass",
        file: "config/physics/priors.yaml",
        path: "mass.chassis_minimum_kg.value",
        value: 800.0,
        unit: "kg",
        valueSource: "UNVERIFIED",
        source: "Widely reported 2026 figure, not yet cited to an FIA document.",
        note: "Total mass is this plus a fuel estimate from M34 — no fuel default is supplied here, since a silent default would make every power estimate wrong by an unseen constant.",
        affects: ["M14 energy twin", "M15 physics calibration hierarchy"],
        inputKind: "number",
        min: 600,
        max: 1000,
        step: 5,
      },
      {
        id: "cda_m2",
        label: "Aerodynamic drag area (CdA), default",
        file: "config/physics/priors.yaml",
        path: "aerodynamics.cda_m2.value",
        value: 1.2,
        unit: "m²",
        valueSource: "UNVERIFIED",
        source: "Literature range 1.0 (low-drag) – 1.4 (high-downforce); midpoint as starting value.",
        note: "The parameter the drag term is most sensitive to at high speed — exactly where envelope violations appear. Raise this first when the violation rate exceeds ~10%.",
        affects: ["M14 energy twin", "M35 override discriminator false-positive rate"],
        inputKind: "number",
        min: 0.8,
        max: 1.6,
        step: 0.01,
      },
      {
        id: "cda_low_drag_m2",
        label: "CdA — low-drag configuration",
        file: "config/physics/priors.yaml",
        path: "aerodynamics.cda_low_drag_m2.value",
        value: 1.0,
        unit: "m²",
        valueSource: "UNVERIFIED",
        source: "Literature range, low-drag configuration (Monza-like).",
        affects: ["M14 energy twin, per-circuit calibration"],
        inputKind: "number",
        min: 0.8,
        max: 1.4,
        step: 0.01,
      },
      {
        id: "cda_high_downforce_m2",
        label: "CdA — high-downforce configuration",
        file: "config/physics/priors.yaml",
        path: "aerodynamics.cda_high_downforce_m2.value",
        value: 1.4,
        unit: "m²",
        valueSource: "UNVERIFIED",
        source: "Literature range, high-downforce configuration (Monaco-like).",
        affects: ["M14 energy twin, per-circuit calibration"],
        inputKind: "number",
        min: 1.0,
        max: 1.8,
        step: 0.01,
      },
      {
        id: "crr",
        label: "Rolling resistance coefficient",
        file: "config/physics/priors.yaml",
        path: "rolling.crr.value",
        value: 0.012,
        valueSource: "UNVERIFIED",
        source: "Literature value for slick racing tyres on asphalt.",
        affects: ["M14 energy twin"],
        inputKind: "number",
        min: 0.005,
        max: 0.03,
        step: 0.001,
      },
      {
        id: "eta_drivetrain",
        label: "Drivetrain efficiency",
        file: "config/physics/priors.yaml",
        path: "drivetrain.eta_drivetrain.value",
        value: 0.92,
        valueSource: "UNVERIFIED",
        source: "Literature estimate for a modern F1 drivetrain.",
        affects: ["M14 energy twin"],
        inputKind: "number",
        min: 0.7,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "eta_deploy",
        label: "Deploy efficiency (Energy Store → wheel)",
        file: "config/physics/priors.yaml",
        path: "drivetrain.eta_deploy.value",
        value: 0.95,
        valueSource: "UNVERIFIED",
        source: "Assumed, calibrated in CP-20.",
        affects: ["C5 ers_deploy_power_est_kw"],
        inputKind: "number",
        min: 0.7,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "eta_harvest",
        label: "Harvest efficiency (wheel → Energy Store)",
        file: "config/physics/priors.yaml",
        path: "drivetrain.eta_harvest.value",
        value: 0.9,
        valueSource: "UNVERIFIED",
        source: "Assumed, calibrated in CP-20. Kept distinct from eta_deploy — the round trip is lossy in both directions.",
        affects: ["C5 ers_harvest_power_est_kw"],
        inputKind: "number",
        min: 0.7,
        max: 1.0,
        step: 0.01,
      },
      {
        id: "p_ice_max_kw",
        label: "ICE maximum power",
        file: "config/physics/priors.yaml",
        path: "engine.p_ice_max_kw.value",
        value: 400.0,
        unit: "kW",
        valueSource: "UNVERIFIED",
        source: "Reported 2026 figure, pending citation.",
        note: "CP-20's fitted rung pins this at a 500 kW bound to lower its violation rate — an engine the regulations do not allow, which is why that rung is rejected rather than accepted.",
        affects: ["M14 energy twin power balance"],
        inputKind: "number",
        min: 300,
        max: 550,
        step: 5,
      },
      {
        id: "gravity_mps2",
        label: "Gravitational acceleration",
        file: "config/physics/priors.yaml",
        path: "environment.gravity_mps2.value",
        value: 9.80665,
        unit: "m/s²",
        valueSource: "OBSERVED",
        source: "ISO 80000-3 standard acceleration of gravity.",
        affects: ["M14 energy twin"],
        inputKind: "number",
        min: 9.7,
        max: 9.9,
        step: 0.00001,
      },
      {
        id: "air_density_fallback_kgm3",
        label: "Air density fallback",
        file: "config/physics/priors.yaml",
        path: "environment.air_density_fallback_kgm3.value",
        value: 1.225,
        unit: "kg/m³",
        valueSource: "UNVERIFIED",
        source: "ISA sea-level standard density, 15°C and 1013.25 hPa.",
        note: "Used only where no weather sample exists for a segment; every such row is flagged air_density_is_fallback. A lap at 35°C and altitude can be ~15% less dense, landing directly on the cube term in drag.",
        affects: ["M14 energy twin", "M33 weather-adjusted physics"],
        inputKind: "number",
        min: 1.0,
        max: 1.3,
        step: 0.005,
      },
    ],
  },
  {
    id: "planner-dp",
    title: "Planner / dynamic-programming value function",
    description:
      "The development-only abstract-utility grid the DP (M22) and beam planner (M24) search over. Explicitly not a calibrated time objective — values here are utility units, never seconds.",
    variables: [
      {
        id: "energy_grid_mj_range",
        label: "Energy grid range",
        file: "config/value/dp_development.yaml",
        path: "energy_grid_mj",
        value: [0.0, 4.0],
        unit: "MJ (41 points, step 0.1)",
        valueSource: "DEVELOPMENT_ONLY",
        source: "development-only abstract-utility grid",
        affects: ["M22 DP state grid", "GET /value/{event}/shadow_price grid.energy_kj"],
        inputKind: "list-number",
      },
      {
        id: "gap_grid_s_range",
        label: "Gap grid range",
        file: "config/value/dp_development.yaml",
        path: "gap_grid_s",
        value: [-3.0, 3.0],
        unit: "s (61 points, step 0.1)",
        valueSource: "DEVELOPMENT_ONLY",
        source: "development-only abstract-utility grid",
        affects: ["M22 DP state grid", "GET /value/{event}/shadow_price grid.gap_s"],
        inputKind: "list-number",
      },
      {
        id: "eligibility_states",
        label: "Eligibility states",
        file: "config/value/dp_development.yaml",
        path: "eligibility_states",
        value: ["0", "1"],
        valueSource: "DEVELOPMENT_ONLY",
        source: "development-only abstract-utility grid",
        affects: ["M22 DP state grid"],
        inputKind: "list-string",
      },
      {
        id: "terminal_ahead_value",
        label: "Terminal utility — ahead value",
        file: "config/value/dp_development.yaml",
        path: "terminal_utility.ahead_value",
        value: 1.0,
        unit: "abstract utility",
        valueSource: "DEVELOPMENT_ONLY",
        source: "development-only abstract-utility grid",
        affects: ["M22 terminal value function", "M24 planner objective"],
        inputKind: "number",
        min: 0,
        max: 5,
        step: 0.1,
      },
      {
        id: "terminal_residual_energy_value",
        label: "Terminal utility — residual energy value",
        file: "config/value/dp_development.yaml",
        path: "terminal_utility.residual_energy_value_per_mj",
        value: 0.01,
        unit: "utility / MJ",
        valueSource: "DEVELOPMENT_ONLY",
        source: "development-only abstract-utility grid",
        affects: ["M22 terminal value function"],
        inputKind: "number",
        min: 0,
        max: 1,
        step: 0.005,
      },
      {
        id: "shadow_finite_difference_delta_mj",
        label: "Shadow-price finite-difference step",
        file: "config/value/dp_development.yaml",
        path: "shadow_finite_difference_delta_mj",
        value: 0.1,
        unit: "MJ",
        valueSource: "DEVELOPMENT_ONLY",
        source: "development-only abstract-utility grid",
        note: "The step size M22 uses to numerically differentiate V(state) into λ_E — too coarse and the spike at a Detection Line gets smeared across segments; too fine and the estimate gets noisy.",
        affects: ["M22 shadow price λ_E"],
        inputKind: "number",
        min: 0.01,
        max: 0.5,
        step: 0.01,
      },
    ],
  },
  {
    id: "state-discretization",
    title: "Strategic-state discretization",
    description:
      "The shared bin edges every consumer of StrategicState (rule engine, DP, planner, simulator) must agree on — one definition, read everywhere, so a state means the same thing across the whole stack.",
    variables: [
      {
        id: "disc_energy_state_mj",
        label: "Energy state bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.energy_state_mj.edges",
        value: [0.0, 1.0, 2.0, 3.0, 4.0],
        unit: "MJ",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["C3–C6 StrategicState binning", "M22 DP grid"],
        inputKind: "list-number",
      },
      {
        id: "disc_tyre_state",
        label: "Tyre state bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.tyre_state.edges",
        value: [-2.0, -0.5, 0.5, 2.0],
        unit: "ratio",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["C3–C6 StrategicState binning"],
        inputKind: "list-number",
      },
      {
        id: "disc_time_gap_s",
        label: "Time gap bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.time_gap_s.edges",
        value: [-3.0, -1.0, -0.25, 0.25, 1.0, 3.0],
        unit: "s",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["C3–C6 StrategicState binning", "M22 DP grid"],
        inputKind: "list-number",
      },
      {
        id: "disc_distance_gap_m",
        label: "Distance gap bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.distance_gap_m.edges",
        value: [-100.0, -25.0, 0.0, 25.0, 100.0],
        unit: "m",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["C3–C6 StrategicState binning"],
        inputKind: "list-number",
      },
      {
        id: "disc_relative_speed_mps",
        label: "Relative speed bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.relative_speed_mps.edges",
        value: [-15.0, -5.0, -1.0, 1.0, 5.0, 15.0],
        unit: "m/s",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["C3–C6 StrategicState binning"],
        inputKind: "list-number",
      },
      {
        id: "disc_gap_rate_s_per_s",
        label: "Gap-rate bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.gap_rate_s_per_s.edges",
        value: [-1.0, -0.2, -0.05, 0.05, 0.2, 1.0],
        unit: "s/s",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["C3–C6 StrategicState binning"],
        inputKind: "list-number",
      },
      {
        id: "disc_horizon",
        label: "Horizon bin edges",
        file: "config/state_discretization.yaml",
        path: "dimensions.horizon.edges",
        value: [0, 1, 3, 6, 12],
        unit: "segments",
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["M24 planner beam depth"],
        inputKind: "list-number",
      },
      {
        id: "disc_overtake_state_categories",
        label: "Overtake-state categories",
        file: "config/state_discretization.yaml",
        path: "dimensions.overtake_state.categories",
        value: ["DISABLED", "UNARMED", "ARMED", "ACTIVE", "UNKNOWN"],
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["M20 Overtake state machine"],
        inputKind: "list-string",
      },
      {
        id: "disc_rival_belief_categories",
        label: "Rival-belief categories",
        file: "config/state_discretization.yaml",
        path: "dimensions.rival_belief.categories",
        value: ["CONSERVING", "BALANCED", "DEPLOYING", "DERATING", "UNKNOWN"],
        valueSource: "DEVELOPMENT_ONLY",
        source: "strategic_state_discretization_v1",
        affects: ["M09 rival-state model", "POST /rival/state"],
        inputKind: "list-string",
      },
    ],
  },
  {
    id: "baselines",
    title: "Driver / team / field baselines",
    description:
      "Minimum sample thresholds before a segment baseline is trusted (M04). Below the threshold, baseline_valid is false rather than a noisy median being shown as a fact.",
    variables: [
      {
        id: "baseline_min_samples_driver",
        label: "Minimum samples — driver baseline",
        file: "config/baselines.yaml",
        path: "minimum_samples.driver",
        value: 15,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "c2_baselines_config_v1",
        affects: ["M04 baseline_valid", "timeline.baseline_residuals.attacker"],
        inputKind: "number",
        min: 1,
        max: 100,
        step: 1,
      },
      {
        id: "baseline_min_samples_team",
        label: "Minimum samples — team baseline",
        file: "config/baselines.yaml",
        path: "minimum_samples.team",
        value: 25,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "c2_baselines_config_v1",
        affects: ["M04 baseline_valid"],
        inputKind: "number",
        min: 1,
        max: 200,
        step: 1,
      },
      {
        id: "baseline_min_samples_field",
        label: "Minimum samples — field baseline",
        file: "config/baselines.yaml",
        path: "minimum_samples.field",
        value: 100,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "c2_baselines_config_v1",
        affects: ["M04 baseline_valid"],
        inputKind: "number",
        min: 1,
        max: 1000,
        step: 10,
      },
    ],
  },
  {
    id: "lap-classification",
    title: "Practice-lap classification",
    description:
      "M01's causal thresholds for labelling a Practice 1 lap PUSH / LONG_RUN / RACE_PACE / COOLDOWN — computed at lap completion from only the current and earlier laps, never relabelled from future tyre behaviour.",
    variables: [
      {
        id: "push_session_best_ratio_max",
        label: "Push — session-best ratio ceiling",
        file: "config/lap_classification.yaml",
        path: "thresholds.push_session_best_ratio_max",
        value: 1.08,
        valueSource: "DEVELOPMENT_ONLY",
        source: "m01_lap_classification_config_v3",
        note: "CP-07 permits this one-percent relaxation after diagnosing UNKNOWN > 30%.",
        affects: ["M01 practice lap classifier", "M15 physics calibration (Practice-only laps)"],
        inputKind: "number",
        min: 1.0,
        max: 1.3,
        step: 0.01,
      },
      {
        id: "push_tyre_life_laps_max",
        label: "Push — max tyre life",
        file: "config/lap_classification.yaml",
        path: "thresholds.push_tyre_life_laps_max",
        value: 5,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m01_lap_classification_config_v3",
        affects: ["M01 practice lap classifier"],
        inputKind: "number",
        min: 1,
        max: 15,
        step: 1,
      },
      {
        id: "cooldown_session_best_ratio_min_exclusive",
        label: "Cooldown — session-best ratio floor (exclusive)",
        file: "config/lap_classification.yaml",
        path: "thresholds.cooldown_session_best_ratio_min_exclusive",
        value: 1.15,
        valueSource: "DEVELOPMENT_ONLY",
        source: "m01_lap_classification_config_v3",
        affects: ["M01 practice lap classifier"],
        inputKind: "number",
        min: 1.0,
        max: 1.5,
        step: 0.01,
      },
      {
        id: "long_run_min_consecutive_laps",
        label: "Long-run — minimum consecutive laps",
        file: "config/lap_classification.yaml",
        path: "thresholds.long_run_min_consecutive_laps",
        value: 4,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m01_lap_classification_config_v3",
        affects: ["M01 practice lap classifier"],
        inputKind: "number",
        min: 2,
        max: 10,
        step: 1,
      },
      {
        id: "long_run_lap_time_spread_ratio_max_exclusive",
        label: "Long-run — lap-time spread ceiling (exclusive)",
        file: "config/lap_classification.yaml",
        path: "thresholds.long_run_lap_time_spread_ratio_max_exclusive",
        value: 0.03,
        valueSource: "DEVELOPMENT_ONLY",
        source: "m01_lap_classification_config_v3",
        affects: ["M01 practice lap classifier"],
        inputKind: "number",
        min: 0.005,
        max: 0.1,
        step: 0.005,
      },
      {
        id: "max_unknown_bridge_laps",
        label: "Max UNKNOWN bridge laps",
        file: "config/lap_classification.yaml",
        path: "long_run.max_unknown_bridge_laps",
        value: 1,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m01_lap_classification_config_v3",
        note: "The one permitted UNKNOWN bridge inside a candidate long run; structural labels always reset the sequence.",
        affects: ["M01 practice lap classifier"],
        inputKind: "number",
        min: 0,
        max: 3,
        step: 1,
      },
    ],
  },
  {
    id: "tyre-pace",
    title: "Tyre-pace context",
    description:
      "M30's causal degradation proxy and normalised pace windows — a comparative context, not a physical tyre sensor. Fuel context stays declared as unavailable rather than corrected with a race-outcome-contaminated value.",
    variables: [
      {
        id: "initial_baseline_retained_laps",
        label: "Initial baseline — retained laps",
        file: "config/tyre_pace.yaml",
        path: "proxy.initial_baseline_retained_laps",
        value: 3,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m30_tyre_pace_config_v1",
        affects: ["M30 tyre_degradation_proxy"],
        inputKind: "number",
        min: 1,
        max: 10,
        step: 1,
      },
      {
        id: "rolling_retained_laps",
        label: "Rolling baseline — retained laps",
        file: "config/tyre_pace.yaml",
        path: "proxy.rolling_retained_laps",
        value: 5,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m30_tyre_pace_config_v1",
        affects: ["M30 tyre_degradation_proxy"],
        inputKind: "number",
        min: 1,
        max: 15,
        step: 1,
      },
      {
        id: "normalised_pace_min_prior_samples",
        label: "Normalised pace — minimum prior samples",
        file: "config/tyre_pace.yaml",
        path: "normalised_pace.minimum_prior_samples",
        value: 3,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m30_tyre_pace_config_v1",
        affects: ["M30 normalised tyre pace", "M06 pairwise tyre features"],
        inputKind: "number",
        min: 1,
        max: 10,
        step: 1,
      },
      {
        id: "similar_tyre_life_laps",
        label: "Similar tyre-life window",
        file: "config/tyre_pace.yaml",
        path: "normalised_pace.similar_tyre_life_laps",
        value: 3,
        unit: "laps",
        valueSource: "DEVELOPMENT_ONLY",
        source: "m30_tyre_pace_config_v1",
        affects: ["M30 normalised tyre pace"],
        inputKind: "number",
        min: 1,
        max: 10,
        step: 1,
      },
    ],
  },
];
