"""Public M10 pass-model boundary (Tanveer CP-14).

Consumers import from here, never from the implementation modules directly, so
the internals can move without breaking CP-15 (calibration), CP-16 (ensemble
spread), CP-17 (era handling), CP-23 (ablation) and the CP-24 service routes,
all of which build on this surface.
"""
from .artifacts import (
    ARTIFACT_SCHEMA_VERSION,
    git_commit,
    load_fit_artifact,
    package_versions,
    write_fit_artifact,
)
from .calibrate import (
    CalibrationSet,
    VariantResult,
    aggregate_variants,
    assert_calibration_disjoint,
    bin_diagnostics,
    crossfit_calibration_set,
    evaluate_variants,
    select_variant,
)
from .calibration import (
    CALIBRATION_SCHEMA_VERSION,
    EPS,
    METHODS,
    MIN_BIN_N,
    MIN_ECE_N,
    MIN_ISOTONIC_N,
    CalibrationError,
    CalibrationFit,
    Calibrator,
    IdentityCalibrator,
    IsotonicCalibrator,
    PlattCalibrator,
    fit_calibrator,
    logit,
    recommended_method,
    sharpness,
    wilson_interval,
)
from .benchmark import (
    FitResult,
    HardwarePlan,
    aggregate,
    fit_cell,
    plan_hardware,
    run_benchmark,
)
from .candidates import (
    CANDIDATES,
    DEFAULT_SEED,
    FAMILIES,
    Candidate,
    PassModel,
    available_families,
    configure_threads,
)
from .features import (
    FEATURE_SCHEMA_VERSION,
    LABEL_COLUMN,
    STRUCTURAL_COLUMNS,
    FeatureSelection,
    FeatureSelectionError,
    build_matrix,
    select_features,
)
from .folds import (
    DESIGNS,
    Fold,
    SplitPlan,
    SplitPlanError,
    assert_disjoint,
    plan_splits,
    resolve_unit,
    summarise,
)
from .metrics import (
    SELECTION_RULE,
    evaluate,
    expected_calibration_error,
    rank_results,
    reliability_table,
)
from .report import check_gates, identity_comparison, render_report

__all__ = [
    "ARTIFACT_SCHEMA_VERSION",
    "CALIBRATION_SCHEMA_VERSION",
    "CANDIDATES",
    "CalibrationError",
    "CalibrationFit",
    "CalibrationSet",
    "Calibrator",
    "Candidate",
    "DEFAULT_SEED",
    "DESIGNS",
    "EPS",
    "FAMILIES",
    "FEATURE_SCHEMA_VERSION",
    "FeatureSelection",
    "FeatureSelectionError",
    "FitResult",
    "Fold",
    "HardwarePlan",
    "IdentityCalibrator",
    "IsotonicCalibrator",
    "LABEL_COLUMN",
    "METHODS",
    "MIN_BIN_N",
    "MIN_ECE_N",
    "MIN_ISOTONIC_N",
    "PassModel",
    "PlattCalibrator",
    "SELECTION_RULE",
    "STRUCTURAL_COLUMNS",
    "SplitPlan",
    "SplitPlanError",
    "VariantResult",
    "aggregate",
    "aggregate_variants",
    "assert_calibration_disjoint",
    "assert_disjoint",
    "available_families",
    "bin_diagnostics",
    "build_matrix",
    "check_gates",
    "configure_threads",
    "crossfit_calibration_set",
    "evaluate",
    "evaluate_variants",
    "expected_calibration_error",
    "fit_calibrator",
    "fit_cell",
    "git_commit",
    "identity_comparison",
    "load_fit_artifact",
    "logit",
    "package_versions",
    "plan_hardware",
    "plan_splits",
    "rank_results",
    "recommended_method",
    "reliability_table",
    "render_report",
    "resolve_unit",
    "run_benchmark",
    "select_features",
    "select_variant",
    "sharpness",
    "summarise",
    "wilson_interval",
    "write_fit_artifact",
]
